module.exports = [
    {code: 'ABCP11', name: 'Grand Plaza Shopping', segment: 'Shopping/Varejo', manager: 'RIO BRAVO'},
    {code: 'AFCR11', name: 'AF Invest Recebíveis Imobiliários', segment: 'Recebíveis Imobiliários', manager: 'CM CAPITAL MARKETS'},
    {code: 'AFOF11', name: 'ALIANZA FOFII', segment: 'Fundo de Fundos', manager: 'BRL TRUST'},
    {code: 'AIEC11', name: 'Autonomy Edifícios Corporativos', segment: 'Lajes Comerciais', manager: 'MODAL'},
    {code: 'ALMI11', name: 'Torre Almirante', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'ALZR11', name: 'Alianza Trust Renda Imobiliária', segment: 'Logisticos', manager: 'BTG PACTUAL'},
    {code: 'ANCR11B', name: 'Ancar IC', segment: 'Shopping/Varejo', manager: 'GERAÇÃO FUTURO'},
    {code: 'AQLL11', name: 'Áquilla', segment: 'Fundo de Fundos', manager: 'ÍNDIGO INVESTIMENTOS'},
    {code: 'ARFI11B', name: 'AQ3 Renda', segment: 'Recebíveis Imobiliários', manager: 'FOCO DTVM'},
    {code: 'ARRI11', name: 'Átrio Reit Recebíveis Imobiliários', segment: 'Recebíveis Imobiliários', manager: 'OLIVEIRA TRUST'},
    {code: 'ATCR11', name: 'HAZ FII', segment: 'Hoteis', manager: 'GRADUAL'},
    {code: 'ATSA11', name: 'Hedge Atrium Shopping Santo André', segment: 'Shopping/Varejo', manager: 'HEDGE INVESTMENTS'},
    {code: 'BARI11', name: 'Barigui Rendimentos', segment: 'Recebíveis Imobiliários', manager: 'OLIVEIRA TRUST'},
    {code: 'BBFI11B', name: 'BB Progressivo', segment: 'Agencias Bancárias', manager: 'BTG PACTUAL'},
    {code: 'BBIM11', name: 'BB Recebíveis Imobiliários', segment: 'Recebíveis Imobiliários', manager: 'BB GESTAO DE RECURSOS DTVM'},
    {code: 'BBPO11', name: 'BB Progressivo II', segment: 'Agencias Bancárias', manager: 'VOTORANTIM ASSET'},
    {code: 'BBRC11', name: 'BB Renda Corporativa', segment: 'Agencias Bancárias', manager: 'VOTORANTIM ASSET'},
    {code: 'BBVJ11', name: 'BB Votorantim Cidade Jardim Continental Tower', segment: 'Lajes Comerciais', manager: 'VOTORANTIM ASSET'},
    {code: 'BCFF11', name: 'BTG Pactual Fundo de Fundos', segment: 'Fundo de Fundos', manager: 'BTG PACTUAL'},
    {code: 'BCIA11', name: 'Bradesco Carteira Imobiliária Ativa', segment: 'Fundo de Fundos', manager: 'BANCO BRADESCO'},
    {code: 'BCRI11', name: 'Banestes Recebíveis Imobiliários', segment: 'Recebíveis Imobiliários', manager: 'BRL TRUST'},
    {code: 'BICR11', name: 'Inter Títulos Imobiliários', segment: 'Recebíveis Imobiliários', manager: 'INTER DTVM'},
    {code: 'BJRC11', name: 'JS Real Estate Recebíveis Imobiliários', segment: 'Recebíveis Imobiliários', manager: 'BANCO J. SAFRA'},
    {code: 'BLCP11', name: 'Bluecap Renda Logística', segment: 'Logisticos', manager: 'BTG PACTUAL'},
    {code: 'BLMO11', name: 'Bluemacaw Office Fund II', segment: 'Lajes Comerciais', manager: 'BRL TRUST'},
    {code: 'BMII11', name: 'Brasílio Machado', segment: 'Lajes Comerciais', manager: 'RIO BRAVO'},
    {code: 'BMLC11B', name: 'BM Brascan Lajes Corporativas', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'BNFS11', name: 'Banrisul Novas Fronteiras', segment: 'Agencias Bancárias', manager: 'OLIVEIRA TRUST'},
    {code: 'BPFF11', name: 'Brasil Plural Absoluto Fundo de Fundos', segment: 'Fundo de Fundos', manager: 'GENIAL INVESTIMENTOS'},
    {code: 'BPMA11', name: 'Brio Prime Malls', segment: 'Shopping/Varejo', manager: 'BRL TRUST'},
    {code: 'BPML11', name: 'BTG Pactual Shoppings', segment: 'Shopping/Varejo', manager: 'BTG PACTUAL'},
    {code: 'BPRP11', name: 'BRLPROP', segment: 'Logisticos', manager: 'BTG PACTUAL'},
    {code: 'BRCO11', name: 'Bresco Logística', segment: 'Logisticos', manager: 'OLIVEIRA TRUST'},
    {code: 'BRCR11', name: 'BTG Pactual Corporate Office Fund', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'BREV11', name: 'Brazil Real Estate Victory Fund I', segment: 'Lajes Comerciais', manager: 'BR-CAPITAL DTVM'},
    {code: 'BRHT11B', name: 'BR Hoteis', segment: 'Hoteis', manager: 'ELITE CCVM'},
    {code: 'BRIM11', name: 'Brio Real Estate II', segment: 'Incorporação Residencial', manager: 'BRL TRUST'},
    {code: 'BTCR11', name: 'BTG Pactual Crédito Imobiliário', segment: 'Recebíveis Imobiliários', manager: 'BTG PACTUAL'},
    {code: 'BTLG11', name: 'BTG Pactual Logística', segment: 'Logisticos', manager: 'BTG PACTUAL'},
    {code: 'BTSG11', name: 'BTSP I', segment: 'Incorporação', manager: 'INTER'},
    {code: 'BVAR11', name: 'Brasil Varejo', segment: 'Lajes Comerciais', manager: 'RIO BRAVO'},
    {code: 'BZLI11', name: 'BRAZIL REALTY', segment: 'Recebíveis Imobiliários', manager: 'FOCO DTVM'},
    {code: 'CARE11', name: 'Brazilian GraveyardDeath Care', segment: 'Outros', manager: 'PLANNER'},
    {code: 'CBOP11', name: 'Castello Branco Office Park', segment: 'Lajes Comerciais', manager: 'CREDIT SUISSE'},
    {code: 'CEOC11', name: 'CEO Cyrela Commercial Properties', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'CJFI11', name: 'CJ FII', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'CNES11', name: 'BM Cenesp', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'CPFF11', name: 'Capitânia REIT FOF', segment: 'Fundo de Fundos', manager: 'VÓRTX'},
    {code: 'CPTS11B', name: 'Capitânia Securities II', segment: 'Recebíveis Imobiliários', manager: 'BTG PACTUAL'},
    {code: 'CRFF11', name: 'Caixa Rio Bravo Fundo de Fundos II', segment: 'Fundo de Fundos', manager: 'CAIXA ECONOMICA FEDERAL'},
    {code: 'CTXT11', name: 'Centro Têxtil Internacional', segment: 'Lajes Comerciais', manager: 'RIO BRAVO'},
    {code: 'CVBI11', name: 'VBI CRI', segment: 'Recebíveis Imobiliários', manager: 'BRL TRUST'},
    {code: 'CXCE11B', name: 'Caixa Cedae', segment: 'Lajes Comerciais', manager: 'CAIXA ECONOMICA FEDERAL'},
    {code: 'CXRI11', name: 'Caixa Rio Bravo Fundo de Fundos', segment: 'Fundo de Fundos', manager: 'CAIXA ECONOMICA FEDERAL'},
    {code: 'CXTL11', name: 'Caixa TRX Logística Renda', segment: 'Logisticos', manager: 'CAIXA ECONOMICA FEDERAL'},
    {code: 'DAMT11B', name: 'Diamante', segment: 'Shopping/Varejo', manager: 'BANCO MODAL S.A.'},
    {code: 'DLMT11', name: 'Del Monte Ajax', segment: 'Lajes Comerciais', manager: 'PLANNER'},
    {code: 'DMAC11', name: 'MAC FII', segment: 'Incorporação Residencial', manager: 'OLIVEIRA TRUST'},
    {code: 'DOMC11', name: 'REAG Renda Imobiliária', segment: 'Lajes Comerciais', manager: 'MONETAR DTVM'},
    {code: 'DOVL11B', name: 'Dovel', segment: 'Lajes Comerciais', manager: 'BNY MELLON'},
    {code: 'DRIT11B', name: 'Multigestão Renda Comercial', segment: 'Lajes Comerciais', manager: 'RIO BRAVO'},
    {code: 'EDFO11B', name: 'Edifício Ourinvest', segment: 'Lajes Comerciais', manager: 'OLIVEIRA TRUST'},
    {code: 'EDGA11', name: 'Edifício Galeria', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'ELDO11B', name: 'Eldorado', segment: 'Shopping/Varejo', manager: 'RIO BRAVO'},
    {code: 'ERPA11', name: 'EUROPA 105', segment: 'Lajes Comerciais', manager: 'OLIVEIRA TRUST'},
    {code: 'ESTQ11', name: 'Polo Estoque II', segment: 'Lajes Comerciais', manager: 'OLIVEIRA TRUST'},
    {code: 'EURO11', name: 'Europar', segment: 'Logisticos', manager: 'COINVALORES'},
    {code: 'FAED11', name: 'Anhanguera Educacional', segment: 'Educacional', manager: 'BTG PACTUAL'},
    {code: 'FAMB11B', name: 'Edifício Almirante Barroso', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'FCAS11', name: 'Edifício Castelo', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'FCFL11', name: 'Campus Faria Lima', segment: 'Educacional', manager: 'BTG PACTUAL'},
    {code: 'FEXC11', name: 'BTG Pactual Fundo de CRI', segment: 'Recebíveis Imobiliários', manager: 'BTG PACTUAL'},
    {code: 'FIGS11', name: 'General Shopping Ativo e Renda', segment: 'Shopping/Varejo', manager: 'HEDGE INVESTMENTS'},
    {code: 'FIIB11', name: 'Industrial do Brasil', segment: 'Logisticos', manager: 'COINVALORES'},
    {code: 'FIIP11B', name: 'RB Capital Renda I', segment: 'Logisticos', manager: 'OLIVEIRA TRUST'},
    {code: 'FINF11', name: 'Infra Real Estate', segment: 'Logisticos', manager: 'PLANNER'},
    {code: 'FISC11', name: 'SC 401', segment: 'Lajes Comerciais', manager: 'CORRETORA GERAL'},
    {code: 'FISD11', name: 'São Domingos', segment: 'Recebíveis Imobiliários', manager: 'FOCO DTVM'},
    {code: 'FIVN11', name: 'Vida Nova', segment: 'Shopping/Varejo', manager: 'OLIVEIRA TRUST'},
    {code: 'FLCR11', name: 'Faria Lima Capital Recebíveis Imobiliários I', segment: 'Recebíveis Imobiliários', manager: 'BRL TRUST'},
    {code: 'FLMA11', name: 'Square Faria Lima', segment: 'Lajes Comerciais', manager: 'BR-CAPITAL DTVM'},
    {code: 'FLRP11', name: 'Floripa Shopping', segment: 'Shopping/Varejo', manager: 'BTG PACTUAL'},
    {code: 'FMOF11', name: 'Memorial Office', segment: 'Lajes Comerciais', manager: 'COINVALORES'},
    {code: 'FOFT11', name: 'Hedge TOP FOFII 2', segment: 'Fundo de Fundos', manager: 'HEDGE INVESTMENTS'},
    {code: 'FPAB11', name: 'Projeto Água Branca', segment: 'Lajes Comerciais', manager: 'COINVALORES'},
    {code: 'FPNG11', name: 'Pedra Negra Renda Imobiliária', segment: 'Lajes Comerciais', manager: 'BR-CAPITAL DTVM'},
    {code: 'FTCE11B', name: 'Opportunity', segment: 'Lajes Comerciais', manager: 'BANCO OPPORTUNITY'},
    {code: 'FTMJ11', name: 'TMJ FII', segment: 'Recebíveis Imobiliários', manager: 'GRADUAL'},
    {code: 'FVBI11', name: 'Fundo VBI FL 4440', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'FVPQ11', name: 'Via Parque', segment: 'Shopping/Varejo', manager: 'RIO BRAVO'},
    {code: 'GCFF11', name: 'Galapagos Fundo de Fundos', segment: 'Fundo de Fundos', manager: 'BTG PACTUAL'},
    {code: 'GESE11', name: 'General Severiano', segment: 'Logisticos', manager: 'OLIVEIRA TRUST'},
    {code: 'GGRC11', name: 'GGR COVEPI', segment: 'Logisticos', manager: 'CM CAPITAL MARKETS'},
    {code: 'GRLV11', name: 'CSHG GR Louveira', segment: 'Logisticos', manager: 'CREDIT SUISSE'},
    {code: 'GSFI11', name: 'General Shopping e Outlets', segment: 'Shopping/Varejo', manager: 'PLANNER'},
    {code: 'GTWR11', name: 'Green Towers', segment: 'Lajes Comerciais', manager: 'VOTORANTIM ASSET'},
    {code: 'GWIC11', name: 'GWI Condomínios Logísticos', segment: 'Logisticos', manager: 'BTG PACTUAL'},
    {code: 'HAAA11', name: 'Hedge AAA', segment: 'Lajes Comerciais', manager: 'HEDGE INVESTMENTS'},
    {code: 'HABT11', name: 'Habitat II', segment: 'Recebíveis Imobiliários', manager: 'VÓRTX'},
    {code: 'HBRH11', name: 'Multi Renda Urbana', segment: 'Lajes Comerciais', manager: 'BRL TRUST'},
    {code: 'HBTT11', name: 'Habitat I', segment: 'Recebíveis Imobiliários', manager: 'VÓRTX'},
    {code: 'HCRI11', name: 'Hospital da Criança', segment: 'Hospital', manager: 'BTG PACTUAL'},
    {code: 'HCTR11', name: 'HECTARE CE', segment: 'Recebíveis Imobiliários', manager: 'VÓRTX'},
    {code: 'HFOF11', name: 'Hedge TOP FOFII 3', segment: 'Fundo de Fundos', manager: 'HEDGE INVESTMENTS'},
    {code: 'HGBS11', name: 'Hedge Brasil Shopping', segment: 'Shopping/Varejo', manager: 'HEDGE INVESTMENTS'},
    {code: 'HGCR11', name: 'CSHG Recebíveis Imobiliários', segment: 'Recebíveis Imobiliários', manager: 'CREDIT SUISSE'},
    {code: 'HGFF11', name: 'CSHG Imobiliário FOF', segment: 'Fundo de Fundos', manager: 'CREDIT SUISSE'},
    {code: 'HGLG11', name: 'CSHG Logística', segment: 'Logisticos', manager: 'CREDIT SUISSE'},
    {code: 'HGPO11', name: 'CSHG Prime Offices', segment: 'Lajes Comerciais', manager: 'CREDIT SUISSE'},
    {code: 'HGRE11', name: 'CSHG Real Estate', segment: 'Lajes Comerciais', manager: 'CREDIT SUISSE'},
    {code: 'HGRU11', name: 'CSHG Renda Urbana', segment: 'Lajes Comerciais', manager: 'CREDIT SUISSE'},
    {code: 'HLOG11', name: 'Hedge Logística', segment: 'Logisticos', manager: 'HEDGE INVESTMENTS'},
    {code: 'HMOC11', name: 'Hedge Shopping Praça da Moça', segment: 'Shopping/Varejo', manager: 'HEDGE INVESTMENTS'},
    {code: 'HOSI11', name: 'Housi', segment: 'Incorporação', manager: 'VÓRTX'},
    {code: 'HPDP11', name: 'Hedge Shopping Parque Dom Pedro', segment: 'Shopping/Varejo', manager: 'HEDGE INVESTMENTS'},
    {code: 'HRDF11', name: 'Hedge Realty Development', segment: 'Incorporação', manager: 'HEDGE INVESTMENTS'},
    {code: 'HREC11', name: 'Hedge Recebíveis Imobiliários', segment: 'Recebíveis Imobiliários', manager: 'HEDGE INVESTMENTS'},
    {code: 'HSML11', name: 'HSI Malls', segment: 'Shopping/Varejo', manager: 'Santander Securities Services'},
    {code: 'HTMX11', name: 'Hotel Maxinvest', segment: 'Hoteis', manager: 'BTG PACTUAL'},
    {code: 'HUSC11', name: 'Hospital Unimed Sul Capixaba', segment: 'Hospital', manager: 'RIO BRAVO'},
    {code: 'HUSI11', name: 'HUSI', segment: 'Hospital', manager: 'PLANNER'},
    {code: 'IBFF11', name: 'FOF Integral Brei', segment: 'Fundo de Fundos', manager: 'BTG PACTUAL'},
    {code: 'IFIX', name: 'IFIX Índice de Fundos Imobiliários', segment: 'N/D', manager: 'N/D'},
    {code: 'IRDM11', name: 'Iridium Recebíveis Imobiliários', segment: 'Recebíveis Imobiliários', manager: 'BTG PACTUAL'},
    {code: 'JPPA11', name: 'JPP Allocaton Mogno', segment: 'Recebíveis Imobiliários', manager: 'VÓRTX'},
    {code: 'JPPC11', name: 'JPP Capital', segment: 'Incorporação', manager: 'BANCO FINAXIS'},
    {code: 'JRDM11', name: 'Shopping Jardim Sul', segment: 'Shopping/Varejo', manager: 'BTG PACTUAL'},
    {code: 'JSIM11', name: 'JS Real Estate Renda Imobiliária', segment: 'Recebíveis Imobiliários', manager: 'BANCO J. SAFRA'},
    {code: 'JSRE11', name: 'JS Real Estate Multigestão', segment: 'Lajes Comerciais', manager: 'BANCO J. SAFRA'},
    {code: 'JTPR11', name: 'JT PREV Desenvolvimento Habitacional', segment: 'Incorporação Residencial', manager: 'PLANNER'},
    {code: 'KFOF11', name: 'Kinea Fundo de Fundos', segment: 'Fundo de Fundos', manager: 'INTRAG'},
    {code: 'KINP11', name: 'Even Permuta Kinea', segment: 'Incorporação Residencial', manager: 'INTRAG'},
    {code: 'KNCR11', name: 'Kinea Rendimentos Imobiliários FII', segment: 'Recebíveis Imobiliários', manager: 'INTRAG'},
    {code: 'KNHY11', name: 'Kinea High Yield CRI', segment: 'Recebíveis Imobiliários', manager: 'INTRAG'},
    {code: 'KNIP11', name: 'Kinea Índices de Preços', segment: 'Recebíveis Imobiliários', manager: 'INTRAG'},
    {code: 'KNRE11', name: 'Kinea II Real Estate Equity', segment: 'Incorporação Residencial', manager: 'INTRAG'},
    {code: 'KNRI11', name: 'Kinea Renda Imobiliária', segment: 'Lajes Comerciais', manager: 'INTRAG'},
    {code: 'LASC11', name: 'Legatus Shoppings', segment: 'Shopping/Varejo', manager: 'VÓRTX'},
    {code: 'LATR11B', name: 'Lateres', segment: 'Incorporação Residencial', manager: 'OLIVEIRA TRUST'},
    {code: 'LGCP11', name: 'LOG CP Inter', segment: 'Logisticos', manager: 'INTER DTVM'},
    {code: 'LOFT11B', name: 'LOFT I (Cota Sênior)', segment: 'Incorporação Residencial', manager: 'MODAL'},
    {code: 'LOFT13B', name: 'LOFT I (Cota Subordinada)', segment: 'Incorporação Residencial', manager: 'MODAL'},
    {code: 'LUGG11', name: 'Luggo', segment: 'Incorporação Residencial', manager: 'INTER DTVM'},
    {code: 'LVBI11', name: 'VBI Logístico', segment: 'Logisticos', manager: 'BTG PACTUAL'},
    {code: 'MALL11', name: 'MALLS BRASIL PLURAL', segment: 'Shopping/Varejo', manager: 'GENIAL INVESTIMENTOS'},
    {code: 'MAXR11', name: 'Max Retail', segment: 'Shopping/Varejo', manager: 'BTG PACTUAL'},
    {code: 'MBRF11', name: 'Mercantil do Brasil', segment: 'Agencias Bancárias', manager: 'RIO BRAVO'},
    {code: 'MCCI11', name: 'Mauá Capital Recebíveis Imobiliários', segment: 'Recebíveis Imobiliários', manager: 'BTG PACTUAL'},
    {code: 'MFII11', name: 'Mérito Desenvolvimento Imobiliário I', segment: 'Incorporação Residencial', manager: 'PLANNER'},
    {code: 'MGFF11', name: 'Mogno Fundo de Fundos', segment: 'Fundo de Fundos', manager: 'BTG PACTUAL'},
    {code: 'MGHT11', name: 'Mogno Hoteis', segment: 'Hoteis', manager: 'BTG PACTUAL'},
    {code: 'MINT11', name: 'Mint Educacional', segment: 'Educacional', manager: 'PLURAL'},
    {code: 'MOFF11', name: 'MULTIOFFICES 2', segment: 'Lajes Comerciais', manager: 'OLIVEIRA TRUST'},
    {code: 'MORE11', name: 'More Real Estate FOF', segment: 'Fundo de Fundos', manager: 'BTG PACTUAL'},
    {code: 'MSHP11', name: 'Mais Shopping Largo 13', segment: 'Shopping/Varejo', manager: 'BEM DTVM'},
    {code: 'MTOF11', name: 'MULTIOFFICES 1', segment: 'Recebíveis Imobiliários', manager: 'OLIVEIRA TRUST'},
    {code: 'MTRS11', name: 'Metropolis', segment: 'Outros', manager: 'BTG PACTUAL'},
    {code: 'MVFI11', name: 'MV9 FII', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'MXRF11', name: 'Maxi Renda', segment: 'Recebíveis Imobiliários', manager: 'BTG PACTUAL'},
    {code: 'NCHB11', name: 'NCH Brasil Recebíveis Imobiliários', segment: 'Recebíveis Imobiliários', manager: 'BTG PACTUAL'},
    {code: 'NEWL11', name: 'Newport Logística', segment: 'Logisticos', manager: 'PLURAL'},
    {code: 'NEWU11', name: 'Newport Renda Urbana', segment: 'Lajes Comerciais', manager: 'N/D'},
    {code: 'NPAR11', name: 'NESTPAR', segment: 'Incorporação', manager: 'PLANNER'},
    {code: 'NSLU11', name: 'Hospital Nossa Senhora de Lourdes', segment: 'Hospital', manager: 'BTG PACTUAL'},
    {code: 'NVHO11', name: 'Novo Horizonte', segment: 'Hospital', manager: 'PLURAL'},
    {code: 'NVIF11B', name: 'Nova I', segment: 'Logisticos', manager: 'MODAL'},
    {code: 'ONEF11', name: 'The One', segment: 'Lajes Comerciais', manager: 'RIO BRAVO'},
    {code: 'ORPD11', name: 'Ouro Preto Desenvolvimento Imobiliário', segment: 'Recebíveis Imobiliários', manager: 'PLANNER'},
    {code: 'OUCY11', name: 'OURINVEST CYRELA', segment: 'Recebíveis Imobiliários', manager: 'BANCO OURINVEST S.A.'},
    {code: 'OUFF11', name: 'Ourinvest Fundo de Fundos', segment: 'Fundo de Fundos', manager: 'BANCO OURINVEST S.A.'},
    {code: 'OUJP11', name: 'Ourinvest JPP', segment: 'Recebíveis Imobiliários', manager: 'FINAXIS CORRETORA'},
    {code: 'OULG11', name: 'Ourinvest Logística', segment: 'Logisticos', manager: 'BANCO OURINVEST S.A.'},
    {code: 'PABY11', name: 'Panamby', segment: 'Incorporação', manager: 'BRKB DTVM'},
    {code: 'PATB11', name: 'Pateo Bandeirantes', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'PATC11', name: 'Pátria Edifícios Corporativos', segment: 'Lajes Comerciais', manager: 'N/D'},
    {code: 'PATL11', name: 'Pátria Logística', segment: 'Logisticos', manager: 'MODAL'},
    {code: 'PBLV11', name: 'Prologis Brazil Logistics Venture', segment: 'Logisticos', manager: 'BRL TRUST'},
    {code: 'PBYR11', name: 'Panamby Renda Master', segment: 'Recebíveis Imobiliários', manager: 'BTG PACTUAL'},
    {code: 'PLCR11', name: 'Plural Recebíveis Imobiliários', segment: 'Recebíveis Imobiliários', manager: 'BRASIL PLURAL'},
    {code: 'PLRI11', name: 'Polo', segment: 'Recebíveis Imobiliários', manager: 'OLIVEIRA TRUST'},
    {code: 'PORD11', name: 'Polo CRI II', segment: 'Recebíveis Imobiliários', manager: 'OLIVEIRA TRUST'},
    {code: 'PQDP11', name: 'Parque Dom Pedro Shopping Center', segment: 'Shopping/Varejo', manager: 'BTG PACTUAL'},
    {code: 'PRGD11', name: 'Icon Realty I', segment: 'Shopping/Varejo', manager: 'Santander Securities Services'},
    {code: 'PRSN11B', name: 'PERSONALE I', segment: 'Incorporação Residencial', manager: 'OLIVEIRA TRUST'},
    {code: 'PRSV11', name: 'Presidente Vargas', segment: 'Lajes Comerciais', manager: 'BEM DTVM'},
    {code: 'PRTS11', name: 'Multi Properties', segment: 'Shopping/Varejo', manager: 'BANCO MODAL S.A.'},
    {code: 'QAGR11', name: 'Quasar Agro', segment: 'Outros', manager: 'BTG PACTUAL'},
    {code: 'QREC11', name: 'Quasar Crédito Imobiliário', segment: 'Recebíveis Imobiliários', manager: 'INTRAG'},
    {code: 'RBAG11', name: 'RB Capital Agre', segment: 'Incorporação Residencial', manager: 'CITIBANK DTVM'},
    {code: 'RBBV11', name: 'JHSF Rio Bravo Fazenda Boa Vista', segment: 'Incorporação', manager: 'CAIXA ECONOMICA FEDERAL'},
    {code: 'RBCB11', name: 'Rio Bravo Crédito Imobiliário I', segment: 'Recebíveis Imobiliários', manager: 'RIO BRAVO'},
    {code: 'RBCO11', name: 'RB Capital Office Income', segment: 'Lajes Comerciais', manager: 'BRL TRUST'},
    {code: 'RBDS11', name: 'RB Capital Desenvolvimento Residencial II', segment: 'Incorporação Residencial', manager: 'OLIVEIRA TRUST'},
    {code: 'RBED11', name: 'Rio Bravo Renda Educacional', segment: 'Educacional', manager: 'RIO BRAVO'},
    {code: 'RBFF11', name: 'Rio Bravo IFIX', segment: 'Fundo de Fundos', manager: 'BRL TRUST'},
    {code: 'RBGS11', name: 'RB Capital General Shopping Sulacap', segment: 'Shopping/Varejo', manager: 'OLIVEIRA TRUST'},
    {code: 'RBIR11', name: 'RB Capital Desenvolvimento Residencial IV', segment: 'Incorporação Residencial', manager: 'OLIVEIRA TRUST'},
    {code: 'RBIV11', name: 'Rio Bravo Crédito Imobiliário IV', segment: 'Recebíveis Imobiliários', manager: 'RIO BRAVO'},
    {code: 'RBPD11', name: 'RB Capital Prime Realty II', segment: 'Recebíveis Imobiliários', manager: 'CITIBANK DTVM'},
    {code: 'RBPR11', name: 'RB Capital Prime Realty I', segment: 'Incorporação Residencial', manager: 'CITIBANK DTVM'},
    {code: 'RBRD11', name: 'RB Capital Renda II', segment: 'Lajes Comerciais', manager: 'VOTORANTIM ASSET'},
    {code: 'RBRF11', name: 'RBR Alpha Multiestratégia Real Estate', segment: 'Fundo de Fundos', manager: 'BTG PACTUAL'},
    {code: 'RBRL11', name: 'RBR LOG', segment: 'Logisticos', manager: 'BRL TRUST'},
    {code: 'RBRM11', name: 'RBR Desenvolvimento', segment: 'Incorporação', manager: 'BTG PACTUAL'},
    {code: 'RBRP11', name: 'RBR Properties FII', segment: 'Lajes Comerciais', manager: 'BRL TRUST'},
    {code: 'RBRR11', name: 'RBR Rendimentos High Grade', segment: 'Recebíveis Imobiliários', manager: 'BTG PACTUAL'},
    {code: 'RBRY11', name: 'RBR Crédito Imobiliário High Yield', segment: 'Recebíveis Imobiliários', manager: 'BTG PACTUAL'},
    {code: 'RBTS11', name: 'RB Capital TFO Situs', segment: 'Incorporação', manager: 'OLIVEIRA TRUST'},
    {code: 'RBVA11', name: 'Rio Bravo Renda Varejo', segment: 'Híbrido', manager: 'RIO BRAVO'},
    {code: 'RBVO11', name: 'Rio Bravo Crédito Imobiliário II', segment: 'Recebíveis Imobiliários', manager: 'RIO BRAVO'},
    {code: 'RCCS11', name: 'REP 1 CCS', segment: 'Shopping/Varejo', manager: 'CREDIT SUISSE'},
    {code: 'RCFA11', name: 'Grupo RCFA', segment: 'Incorporação', manager: 'Fram Capital'},
    {code: 'RCFF11', name: 'RBR Desenvolvimento Comercial Feeder FOF', segment: 'Fundo de Fundos', manager: 'BRL TRUST'},
    {code: 'RCRB11', name: 'Rio Bravo Renda Corporativa', segment: 'Lajes Comerciais', manager: 'RIO BRAVO'},
    {code: 'RCRI11', name: 'RB Capital Rendimentos', segment: 'Recebíveis Imobiliários', manager: 'OLIVEIRA TRUST'},
    {code: 'RDPD11', name: 'Fundo BB Renda de Papéis II', segment: 'Recebíveis Imobiliários', manager: 'VOTORANTIM ASSET'},
    {code: 'RECT11', name: 'UBS BR OFFICE', segment: 'Lajes Comerciais', manager: 'BRL TRUST'},
    {code: 'REIT11', name: 'SOCOPA FII', segment: 'Recebíveis Imobiliários', manager: 'BNY MELLON'},
    {code: 'RFOF11', name: 'RB Capital I Fundo de Fundos', segment: 'Fundo de Fundos', manager: 'BRL TRUST'},
    {code: 'RNDP11', name: 'Fundo BB Renda de Papéis', segment: 'Recebíveis Imobiliários', manager: 'VOTORANTIM ASSET'},
    {code: 'RNGO11', name: 'Rio Negro', segment: 'Lajes Comerciais', manager: 'RIO BRAVO'},
    {code: 'RRCI11', name: 'RB Capital Recebíveis Imobiliários', segment: 'Recebíveis Imobiliários', manager: 'BRL TRUST'},
    {code: 'RSBU11B', name: 'RSB 1', segment: 'Híbrido', manager: 'NSG CAPITAL DTVM'},
    {code: 'RSPD11', name: 'RB Capital Desenvolvimento Residencial III', segment: 'Incorporação Residencial', manager: 'OLIVEIRA TRUST'},
    {code: 'RVBI11', name: 'VBI REITS FOF', segment: 'Fundo de Fundos', manager: 'BRL TRUST'},
    {code: 'SAAG11', name: 'Santander Agências', segment: 'Agencias Bancárias', manager: 'RIO BRAVO'},
    {code: 'SADI11', name: 'Santander Papéis Imobiliários CDI', segment: 'Recebíveis Imobiliários', manager: 'Santander Securities Services'},
    {code: 'SAIC11B', name: 'SIA Corporate', segment: 'Lajes Comerciais', manager: 'BRB DTVM'},
    {code: 'SARE11', name: 'Santander Renda de Aluguéis', segment: 'Lajes Comerciais', manager: 'Santander Securities Services'},
    {code: 'SCPF11', name: 'SCP', segment: 'Shopping/Varejo', manager: 'BR-CAPITAL DTVM'},
    {code: 'SDIL11', name: 'SDI Rio Bravo Renda Logística', segment: 'Logisticos', manager: 'RIO BRAVO'},
    {code: 'SFND11', name: 'São Fernando', segment: 'Lajes Comerciais', manager: 'RIO BRAVO'},
    {code: 'SHDP11B', name: 'Shopping Parque Dom Pedro', segment: 'Shopping/Varejo', manager: 'BTG PACTUAL'},
    {code: 'SHOP11', name: 'Multi Shoppings', segment: 'Shopping/Varejo', manager: 'MODAL'},
    {code: 'SHPH11', name: 'Shopping Pátio Higienópolis', segment: 'Shopping/Varejo', manager: 'RIO BRAVO'},
    {code: 'SPAF11', name: 'Spa', segment: 'Shopping/Varejo', manager: 'PLURAL'},
    {code: 'SPTW11', name: 'SP Downtown', segment: 'Lajes Comerciais', manager: 'GERAÇÃO FUTURO'},
    {code: 'SPVJ11', name: 'Succespar Varejo', segment: 'Shopping/Varejo', manager: 'VÓRTX'},
    {code: 'STFI11', name: 'Santander Recebíveis Imobiliários', segment: 'Recebíveis Imobiliários', manager: 'Santander Securities Services'},
    {code: 'STRX11', name: 'StarX', segment: 'Shopping/Varejo', manager: 'OLIVEIRA TRUST'},
    {code: 'TBOF11', name: 'TB Office', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'TCPF11', name: 'Treecorp Real Estate I', segment: 'Incorporação', manager: 'BR-CAPITAL DTVM'},
    {code: 'TEPP11', name: 'Tellus Properties', segment: 'Lajes Comerciais', manager: 'BRL TRUST'},
    {code: 'TFOF11', name: 'Hedge TOP FOFII', segment: 'Fundo de Fundos', manager: 'HEDGE INVESTMENTS'},
    {code: 'TGAR11', name: 'TG Ativo Real', segment: 'Incorporação', manager: 'VÓRTX'},
    {code: 'THRA11', name: 'BM Cyrela Thera Corporate', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'TORD11', name: 'TORDESILHAS EI', segment: 'Híbrido', manager: 'VÓRTX'},
    {code: 'TORM11', name: 'Tourmalet I', segment: 'Incorporação', manager: 'VÓRTX'},
    {code: 'TOUR11', name: 'Tourmalet II', segment: 'Incorporação', manager: 'VÓRTX'},
    {code: 'TRNT11', name: 'Torre Norte', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'TRXB11', name: 'TRX Real Estate II', segment: 'Logisticos', manager: 'BRL TRUST'},
    {code: 'TRXF11', name: 'TRX Real Estate', segment: 'Logisticos', manager: 'BRL TRUST'},
    {code: 'TSNC11', name: 'Transinc', segment: 'Lajes Comerciais', manager: 'BANCO FINAXIS'},
    {code: 'UBSR11', name: 'UBS BR Recebíveis', segment: 'Recebíveis Imobiliários', manager: 'BRL TRUST'},
    {code: 'URBN11', name: 'Urbaniza', segment: 'Incorporação', manager: 'FOCO DTVM'},
    {code: 'URPR11', name: 'Urca Prime Renda', segment: 'Híbrido', manager: 'VÓRTX'},
    {code: 'VCJR11', name: 'Vectis Juros Real', segment: 'Recebíveis Imobiliários', manager: 'INTRAG'},
    {code: 'VERE11', name: 'VEREDA', segment: 'Lajes Comerciais', manager: 'RIO BRAVO'},
    {code: 'VGIP11', name: 'Valora CRI Índice de Preço', segment: 'Recebíveis Imobiliários', manager: 'BTG PACTUAL'},
    {code: 'VGIR11', name: 'VALORA RE III', segment: 'Recebíveis Imobiliários', manager: 'BTG PACTUAL'},
    {code: 'VIDS11', name: 'Vic Desenvolvimento - Vintage 20/21', segment: 'Incorporação', manager: 'BRASIL PLURAL'},
    {code: 'VIFI11', name: 'Vinci Instrumentos Financeiros', segment: 'Recebíveis Imobiliários', manager: 'BRL TRUST'},
    {code: 'VILG11', name: 'Vinci Logística', segment: 'Logisticos', manager: 'BRL TRUST'},
    {code: 'VINO11', name: 'Vinci Offices', segment: 'Lajes Comerciais', manager: 'BRL TRUST'},
    {code: 'VISC11', name: 'Vinci Shopping Centers', segment: 'Shopping/Varejo', manager: 'BRL TRUST'},
    {code: 'VLJS11', name: 'Vector Queluz Lajes Corporativas', segment: 'Lajes Comerciais', manager: 'PLANNER'},
    {code: 'VLOL11', name: 'Vila Olímpia Corporate', segment: 'Lajes Comerciais', manager: 'OLIVEIRA TRUST'},
    {code: 'VOTS11', name: 'Votorantim Securities Master', segment: 'Recebíveis Imobiliários', manager: 'VOTORANTIM ASSET'},
    {code: 'VPSI11', name: 'Polo Shopping Indaiatuba', segment: 'Shopping/Varejo', manager: 'VOTORANTIM ASSET'},
    {code: 'VRTA11', name: 'Fator Verità', segment: 'Recebíveis Imobiliários', manager: 'BANCO FATOR'},
    {code: 'VSEC11', name: 'Votorantim Securities', segment: 'Recebíveis Imobiliários', manager: 'VOTORANTIM ASSET'},
    {code: 'VSHO11', name: 'Votorantim Shopping', segment: 'Shopping/Varejo', manager: 'VOTORANTIM ASSET'},
    {code: 'VTLT11', name: 'Votorantim Logística', segment: 'Logisticos', manager: 'VOTORANTIM ASSET'},
    {code: 'VTPA11', name: 'Votorantim Patrimonial V', segment: 'Lajes Comerciais', manager: 'VOTORANTIM ASSET'},
    {code: 'VTPL11', name: 'FII PLUS', segment: 'Logisticos', manager: 'BTG PACTUAL'},
    {code: 'VTVI11', name: 'Parking Partners', segment: 'Shopping/Varejo', manager: 'VOTORANTIM ASSET'},
    {code: 'VTXI11', name: 'Votorantim Patrimonial XII', segment: 'Incorporação', manager: 'VOTORANTIM ASSET'},
    {code: 'VVPR11', name: 'V2 Properties', segment: 'Logisticos', manager: 'BTG PACTUAL'},
    {code: 'VXXV11', name: 'VX XVI', segment: 'Incorporação', manager: 'VÓRTX'},
    {code: 'WMRB11B', name: 'WM RB Capital', segment: 'Recebíveis Imobiliários', manager: 'CITIBANK DTVM'},
    {code: 'WPLZ11', name: 'West Plaza', segment: 'Shopping/Varejo', manager: 'HEDGE INVESTMENTS'},
    {code: 'WTSP11B', name: 'Ourinvest RE I', segment: 'Lajes Comerciais', manager: 'BANCO OURINVEST S.A.'},
    {code: 'XPCI11', name: 'XP Crédito', segment: 'Recebíveis Imobiliários', manager: 'VÓRTX'},
    {code: 'XPCM11', name: 'XP Corporate Macaé', segment: 'Lajes Comerciais', manager: 'RIO BRAVO'},
    {code: 'XPGA11', name: 'XP Recebíveis', segment: 'Recebíveis Imobiliários', manager: 'CITIBANK DTVM'},
    {code: 'XPHT11', name: 'XP Hotéis (Cota Sênior)', segment: 'Hoteis', manager: 'GENIAL INVESTIMENTOS'},
    {code: 'XPHT12', name: 'XP Hotéis (Cota Ordinária)', segment: 'Hoteis', manager: 'GENIAL INVESTIMENTOS'},
    {code: 'XPIN11', name: 'XP Industrial', segment: 'Logisticos', manager: 'VÓRTX'},
    {code: 'XPLG11', name: 'XP LOG', segment: 'Logisticos', manager: 'VÓRTX'},
    {code: 'XPML11', name: 'XP Malls', segment: 'Shopping/Varejo', manager: 'BTG PACTUAL'},
    {code: 'XPPR11', name: 'XP Properties', segment: 'Lajes Comerciais', manager: 'VÓRTX'},
    {code: 'XPSF11', name: 'XP Selection', segment: 'Fundo de Fundos', manager: 'VÓRTX'},
    {code: 'XTED11', name: 'TRX Edifícios Corporativos', segment: 'Lajes Comerciais', manager: 'BTG PACTUAL'},
    {code: 'YCHY11', name: 'Yaguara Capital High Yield', segment: 'Logisticos', manager: 'VÓRTX'},
];